export type RouteRecord = {
  slug: string; // e.g. "california-to-texas"
  from: string; // state slug
  to: string;   // state slug
  fromName: string;
  toName: string;
  distanceMiles: number;
  transitDays: string; // e.g. "5–8"
  openPrice: string;   // e.g. "$850 – $1,150"
  enclosedPrice: string;
  topCitiesFrom: string[];
  topCitiesTo: string[];
  notes?: string;
};

export const routesData: RouteRecord[] = [
  // CA ↔ major states
  { slug:"california-to-new-york", from:"california", to:"new-york", fromName:"California", toName:"New York", distanceMiles:2800, transitDays:"7–10", openPrice:"$1,050–$1,400", enclosedPrice:"$1,600–$2,100", topCitiesFrom:["Los Angeles","San Francisco","San Diego"], topCitiesTo:["New York City","Buffalo","Albany"] },
  { slug:"new-york-to-california", from:"new-york", to:"california", fromName:"New York", toName:"California", distanceMiles:2800, transitDays:"7–10", openPrice:"$1,050–$1,400", enclosedPrice:"$1,600–$2,100", topCitiesFrom:["New York City","Buffalo","Albany"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"california-to-texas", from:"california", to:"texas", fromName:"California", toName:"Texas", distanceMiles:1400, transitDays:"4–7", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,500", topCitiesFrom:["Los Angeles","San Diego","San Francisco"], topCitiesTo:["Houston","Dallas","San Antonio"] },
  { slug:"texas-to-california", from:"texas", to:"california", fromName:"Texas", toName:"California", distanceMiles:1400, transitDays:"4–7", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,500", topCitiesFrom:["Houston","Dallas","San Antonio"], topCitiesTo:["Los Angeles","San Diego","San Francisco"] },
  { slug:"california-to-florida", from:"california", to:"florida", fromName:"California", toName:"Florida", distanceMiles:2750, transitDays:"7–10", openPrice:"$1,000–$1,350", enclosedPrice:"$1,550–$2,050", topCitiesFrom:["Los Angeles","San Diego","San Francisco"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-california", from:"florida", to:"california", fromName:"Florida", toName:"California", distanceMiles:2750, transitDays:"7–10", openPrice:"$1,000–$1,350", enclosedPrice:"$1,550–$2,050", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Los Angeles","San Diego","San Francisco"] },
  { slug:"california-to-illinois", from:"california", to:"illinois", fromName:"California", toName:"Illinois", distanceMiles:2000, transitDays:"5–8", openPrice:"$900–$1,200", enclosedPrice:"$1,400–$1,850", topCitiesFrom:["Los Angeles","San Francisco","San Diego"], topCitiesTo:["Chicago","Aurora","Springfield"] },
  { slug:"illinois-to-california", from:"illinois", to:"california", fromName:"Illinois", toName:"California", distanceMiles:2000, transitDays:"5–8", openPrice:"$900–$1,200", enclosedPrice:"$1,400–$1,850", topCitiesFrom:["Chicago","Aurora","Springfield"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"california-to-washington", from:"california", to:"washington", fromName:"California", toName:"Washington", distanceMiles:1100, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,300", topCitiesFrom:["Los Angeles","San Francisco","San Diego"], topCitiesTo:["Seattle","Tacoma","Spokane"] },
  { slug:"washington-to-california", from:"washington", to:"california", fromName:"Washington", toName:"California", distanceMiles:1100, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,300", topCitiesFrom:["Seattle","Tacoma","Spokane"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"california-to-arizona", from:"california", to:"arizona", fromName:"California", toName:"Arizona", distanceMiles:380, transitDays:"1–3", openPrice:"$350–$550", enclosedPrice:"$600–$850", topCitiesFrom:["Los Angeles","San Diego","Riverside"], topCitiesTo:["Phoenix","Tucson","Scottsdale"] },
  { slug:"arizona-to-california", from:"arizona", to:"california", fromName:"Arizona", toName:"California", distanceMiles:380, transitDays:"1–3", openPrice:"$350–$550", enclosedPrice:"$600–$850", topCitiesFrom:["Phoenix","Tucson","Scottsdale"], topCitiesTo:["Los Angeles","San Diego","Riverside"] },
  { slug:"california-to-colorado", from:"california", to:"colorado", fromName:"California", toName:"Colorado", distanceMiles:1050, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Los Angeles","San Francisco","San Diego"], topCitiesTo:["Denver","Colorado Springs","Boulder"] },
  { slug:"colorado-to-california", from:"colorado", to:"california", fromName:"Colorado", toName:"California", distanceMiles:1050, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Denver","Colorado Springs","Boulder"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },

  // FL snowbird routes
  { slug:"new-york-to-florida", from:"new-york", to:"florida", fromName:"New York", toName:"Florida", distanceMiles:1280, transitDays:"3–6", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,450", topCitiesFrom:["New York City","Buffalo","Rochester"], topCitiesTo:["Miami","Orlando","Tampa","Naples"], notes:"Peak demand October–December southbound. Book 3–6 weeks early." },
  { slug:"florida-to-new-york", from:"florida", to:"new-york", fromName:"Florida", toName:"New York", distanceMiles:1280, transitDays:"3–6", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,450", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["New York City","Buffalo","Rochester"], notes:"Peak demand March–May northbound." },
  { slug:"illinois-to-florida", from:"illinois", to:"florida", fromName:"Illinois", toName:"Florida", distanceMiles:1300, transitDays:"3–6", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,450", topCitiesFrom:["Chicago","Naperville","Rockford"], topCitiesTo:["Miami","Orlando","Tampa","Naples"], notes:"One of the highest-volume snowbird corridors in the US." },
  { slug:"florida-to-illinois", from:"florida", to:"illinois", fromName:"Florida", toName:"Illinois", distanceMiles:1300, transitDays:"3–6", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,450", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Chicago","Naperville","Rockford"] },
  { slug:"ohio-to-florida", from:"ohio", to:"florida", fromName:"Ohio", toName:"Florida", distanceMiles:1100, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Columbus","Cleveland","Cincinnati"], topCitiesTo:["Miami","Orlando","Tampa"], notes:"Peak demand October–December southbound." },
  { slug:"florida-to-ohio", from:"florida", to:"ohio", fromName:"Florida", toName:"Ohio", distanceMiles:1100, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Columbus","Cleveland","Cincinnati"] },
  { slug:"michigan-to-florida", from:"michigan", to:"florida", fromName:"Michigan", toName:"Florida", distanceMiles:1300, transitDays:"3–6", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,450", topCitiesFrom:["Detroit","Grand Rapids","Ann Arbor"], topCitiesTo:["Miami","Orlando","Naples","Fort Myers"], notes:"High snowbird volume October–December." },
  { slug:"florida-to-michigan", from:"florida", to:"michigan", fromName:"Florida", toName:"Michigan", distanceMiles:1300, transitDays:"3–6", openPrice:"$700–$1,000", enclosedPrice:"$1,100–$1,450", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Detroit","Grand Rapids","Ann Arbor"] },
  { slug:"pennsylvania-to-florida", from:"pennsylvania", to:"florida", fromName:"Pennsylvania", toName:"Florida", distanceMiles:1200, transitDays:"3–6", openPrice:"$650–$950", enclosedPrice:"$1,050–$1,400", topCitiesFrom:["Philadelphia","Pittsburgh","Allentown"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-pennsylvania", from:"florida", to:"pennsylvania", fromName:"Florida", toName:"Pennsylvania", distanceMiles:1200, transitDays:"3–6", openPrice:"$650–$950", enclosedPrice:"$1,050–$1,400", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Philadelphia","Pittsburgh","Allentown"] },
  { slug:"new-jersey-to-florida", from:"new-jersey", to:"florida", fromName:"New Jersey", toName:"Florida", distanceMiles:1200, transitDays:"3–6", openPrice:"$650–$950", enclosedPrice:"$1,050–$1,400", topCitiesFrom:["Newark","Jersey City","Trenton"], topCitiesTo:["Miami","Orlando","Fort Lauderdale"] },
  { slug:"florida-to-new-jersey", from:"florida", to:"new-jersey", fromName:"Florida", toName:"New Jersey", distanceMiles:1200, transitDays:"3–6", openPrice:"$650–$950", enclosedPrice:"$1,050–$1,400", topCitiesFrom:["Miami","Orlando","Fort Lauderdale"], topCitiesTo:["Newark","Jersey City","Trenton"] },
  { slug:"massachusetts-to-florida", from:"massachusetts", to:"florida", fromName:"Massachusetts", toName:"Florida", distanceMiles:1500, transitDays:"4–7", openPrice:"$800–$1,100", enclosedPrice:"$1,250–$1,650", topCitiesFrom:["Boston","Worcester","Springfield"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-massachusetts", from:"florida", to:"massachusetts", fromName:"Florida", toName:"Massachusetts", distanceMiles:1500, transitDays:"4–7", openPrice:"$800–$1,100", enclosedPrice:"$1,250–$1,650", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Boston","Worcester","Springfield"] },
  { slug:"connecticut-to-florida", from:"connecticut", to:"florida", fromName:"Connecticut", toName:"Florida", distanceMiles:1350, transitDays:"4–6", openPrice:"$750–$1,050", enclosedPrice:"$1,150–$1,550", topCitiesFrom:["Hartford","Bridgeport","New Haven"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-connecticut", from:"florida", to:"connecticut", fromName:"Florida", toName:"Connecticut", distanceMiles:1350, transitDays:"4–6", openPrice:"$750–$1,050", enclosedPrice:"$1,150–$1,550", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Hartford","Bridgeport","New Haven"] },
  { slug:"maine-to-florida", from:"maine", to:"florida", fromName:"Maine", toName:"Florida", distanceMiles:1600, transitDays:"4–7", openPrice:"$850–$1,150", enclosedPrice:"$1,300–$1,700", topCitiesFrom:["Portland","Lewiston","Bangor"], topCitiesTo:["Miami","Orlando","Naples"], notes:"One of the longest Northeast snowbird corridors." },
  { slug:"florida-to-maine", from:"florida", to:"maine", fromName:"Florida", toName:"Maine", distanceMiles:1600, transitDays:"4–7", openPrice:"$850–$1,150", enclosedPrice:"$1,300–$1,700", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Portland","Lewiston","Bangor"] },

  // Snowbird → Arizona
  { slug:"illinois-to-arizona", from:"illinois", to:"arizona", fromName:"Illinois", toName:"Arizona", distanceMiles:1800, transitDays:"5–7", openPrice:"$900–$1,200", enclosedPrice:"$1,350–$1,800", topCitiesFrom:["Chicago","Naperville","Rockford"], topCitiesTo:["Phoenix","Scottsdale","Tucson"], notes:"High snowbird demand October–December." },
  { slug:"michigan-to-arizona", from:"michigan", to:"arizona", fromName:"Michigan", toName:"Arizona", distanceMiles:1900, transitDays:"5–8", openPrice:"$900–$1,250", enclosedPrice:"$1,400–$1,850", topCitiesFrom:["Detroit","Grand Rapids","Lansing"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"ohio-to-arizona", from:"ohio", to:"arizona", fromName:"Ohio", toName:"Arizona", distanceMiles:1900, transitDays:"5–8", openPrice:"$900–$1,250", enclosedPrice:"$1,400–$1,850", topCitiesFrom:["Columbus","Cleveland","Cincinnati"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"minnesota-to-arizona", from:"minnesota", to:"arizona", fromName:"Minnesota", toName:"Arizona", distanceMiles:1850, transitDays:"5–7", openPrice:"$900–$1,200", enclosedPrice:"$1,350–$1,800", topCitiesFrom:["Minneapolis","Saint Paul","Rochester"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"new-york-to-arizona", from:"new-york", to:"arizona", fromName:"New York", toName:"Arizona", distanceMiles:2400, transitDays:"6–9", openPrice:"$1,000–$1,350", enclosedPrice:"$1,550–$2,000", topCitiesFrom:["New York City","Buffalo","Rochester"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"pennsylvania-to-arizona", from:"pennsylvania", to:"arizona", fromName:"Pennsylvania", toName:"Arizona", distanceMiles:2300, transitDays:"6–9", openPrice:"$1,000–$1,350", enclosedPrice:"$1,550–$2,000", topCitiesFrom:["Philadelphia","Pittsburgh","Allentown"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"massachusetts-to-arizona", from:"massachusetts", to:"arizona", fromName:"Massachusetts", toName:"Arizona", distanceMiles:2650, transitDays:"7–10", openPrice:"$1,050–$1,400", enclosedPrice:"$1,600–$2,100", topCitiesFrom:["Boston","Worcester","Springfield"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"wisconsin-to-arizona", from:"wisconsin", to:"arizona", fromName:"Wisconsin", toName:"Arizona", distanceMiles:1850, transitDays:"5–7", openPrice:"$900–$1,200", enclosedPrice:"$1,350–$1,800", topCitiesFrom:["Milwaukee","Madison","Green Bay"], topCitiesTo:["Phoenix","Scottsdale","Tucson"] },
  { slug:"minnesota-to-florida", from:"minnesota", to:"florida", fromName:"Minnesota", toName:"Florida", distanceMiles:1600, transitDays:"4–7", openPrice:"$850–$1,150", enclosedPrice:"$1,300–$1,700", topCitiesFrom:["Minneapolis","Saint Paul","Rochester"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-minnesota", from:"florida", to:"minnesota", fromName:"Florida", toName:"Minnesota", distanceMiles:1600, transitDays:"4–7", openPrice:"$850–$1,150", enclosedPrice:"$1,300–$1,700", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Minneapolis","Saint Paul","Rochester"] },
  { slug:"wisconsin-to-florida", from:"wisconsin", to:"florida", fromName:"Wisconsin", toName:"Florida", distanceMiles:1500, transitDays:"4–7", openPrice:"$800–$1,100", enclosedPrice:"$1,250–$1,650", topCitiesFrom:["Milwaukee","Madison","Green Bay"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-wisconsin", from:"florida", to:"wisconsin", fromName:"Florida", toName:"Wisconsin", distanceMiles:1500, transitDays:"4–7", openPrice:"$800–$1,100", enclosedPrice:"$1,250–$1,650", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Milwaukee","Madison","Green Bay"] },

  // TX routes
  { slug:"texas-to-new-york", from:"texas", to:"new-york", fromName:"Texas", toName:"New York", distanceMiles:1750, transitDays:"4–7", openPrice:"$900–$1,200", enclosedPrice:"$1,350–$1,800", topCitiesFrom:["Houston","Dallas","San Antonio"], topCitiesTo:["New York City","Buffalo","Albany"] },
  { slug:"new-york-to-texas", from:"new-york", to:"texas", fromName:"New York", toName:"Texas", distanceMiles:1750, transitDays:"4–7", openPrice:"$900–$1,200", enclosedPrice:"$1,350–$1,800", topCitiesFrom:["New York City","Buffalo","Albany"], topCitiesTo:["Houston","Dallas","San Antonio"] },
  { slug:"texas-to-florida", from:"texas", to:"florida", fromName:"Texas", toName:"Florida", distanceMiles:1100, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Houston","Dallas","San Antonio"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-texas", from:"florida", to:"texas", fromName:"Florida", toName:"Texas", distanceMiles:1100, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Houston","Dallas","San Antonio"] },
  { slug:"texas-to-illinois", from:"texas", to:"illinois", fromName:"Texas", toName:"Illinois", distanceMiles:1000, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Houston","Dallas","Austin"], topCitiesTo:["Chicago","Aurora","Springfield"] },
  { slug:"illinois-to-texas", from:"illinois", to:"texas", fromName:"Illinois", toName:"Texas", distanceMiles:1000, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Chicago","Aurora","Springfield"], topCitiesTo:["Houston","Dallas","Austin"] },
  { slug:"colorado-to-texas", from:"colorado", to:"texas", fromName:"Colorado", toName:"Texas", distanceMiles:750, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Denver","Colorado Springs","Boulder"], topCitiesTo:["Dallas","Houston","Austin"] },
  { slug:"texas-to-colorado", from:"texas", to:"colorado", fromName:"Texas", toName:"Colorado", distanceMiles:750, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Dallas","Houston","Austin"], topCitiesTo:["Denver","Colorado Springs","Boulder"] },
  { slug:"nevada-to-texas", from:"nevada", to:"texas", fromName:"Nevada", toName:"Texas", distanceMiles:1250, transitDays:"3–5", openPrice:"$700–$950", enclosedPrice:"$1,050–$1,400", topCitiesFrom:["Las Vegas","Reno","Henderson"], topCitiesTo:["Houston","Dallas","San Antonio"] },
  { slug:"washington-to-texas", from:"washington", to:"texas", fromName:"Washington", toName:"Texas", distanceMiles:2000, transitDays:"5–8", openPrice:"$950–$1,250", enclosedPrice:"$1,450–$1,900", topCitiesFrom:["Seattle","Tacoma","Spokane"], topCitiesTo:["Houston","Dallas","Austin"] },
  { slug:"washington-to-arizona", from:"washington", to:"arizona", fromName:"Washington", toName:"Arizona", distanceMiles:1400, transitDays:"3–6", openPrice:"$750–$1,000", enclosedPrice:"$1,150–$1,500", topCitiesFrom:["Seattle","Tacoma","Bellevue"], topCitiesTo:["Phoenix","Tucson","Scottsdale"], notes:"Popular snowbird route from Pacific Northwest." },
  { slug:"oregon-to-california", from:"oregon", to:"california", fromName:"Oregon", toName:"California", distanceMiles:600, transitDays:"2–3", openPrice:"$450–$650", enclosedPrice:"$750–$1,000", topCitiesFrom:["Portland","Salem","Eugene"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"california-to-oregon", from:"california", to:"oregon", fromName:"California", toName:"Oregon", distanceMiles:600, transitDays:"2–3", openPrice:"$450–$650", enclosedPrice:"$750–$1,000", topCitiesFrom:["Los Angeles","San Francisco","San Diego"], topCitiesTo:["Portland","Salem","Eugene"] },
  { slug:"oregon-to-arizona", from:"oregon", to:"arizona", fromName:"Oregon", toName:"Arizona", distanceMiles:1300, transitDays:"3–5", openPrice:"$700–$950", enclosedPrice:"$1,050–$1,400", topCitiesFrom:["Portland","Salem","Eugene"], topCitiesTo:["Phoenix","Tucson","Scottsdale"] },

  // Southeast / Northeast corridors
  { slug:"georgia-to-florida", from:"georgia", to:"florida", fromName:"Georgia", toName:"Florida", distanceMiles:340, transitDays:"1–3", openPrice:"$350–$550", enclosedPrice:"$600–$850", topCitiesFrom:["Atlanta","Savannah","Augusta"], topCitiesTo:["Jacksonville","Orlando","Miami"] },
  { slug:"florida-to-georgia", from:"florida", to:"georgia", fromName:"Florida", toName:"Georgia", distanceMiles:340, transitDays:"1–3", openPrice:"$350–$550", enclosedPrice:"$600–$850", topCitiesFrom:["Jacksonville","Orlando","Miami"], topCitiesTo:["Atlanta","Savannah","Augusta"] },
  { slug:"georgia-to-new-york", from:"georgia", to:"new-york", fromName:"Georgia", toName:"New York", distanceMiles:950, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Atlanta","Savannah","Augusta"], topCitiesTo:["New York City","Buffalo","Albany"] },
  { slug:"new-york-to-georgia", from:"new-york", to:"georgia", fromName:"New York", toName:"Georgia", distanceMiles:950, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["New York City","Buffalo","Albany"], topCitiesTo:["Atlanta","Savannah","Augusta"] },
  { slug:"north-carolina-to-florida", from:"north-carolina", to:"florida", fromName:"North Carolina", toName:"Florida", distanceMiles:700, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Charlotte","Raleigh","Greensboro"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-north-carolina", from:"florida", to:"north-carolina", fromName:"Florida", toName:"North Carolina", distanceMiles:700, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Charlotte","Raleigh","Greensboro"] },
  { slug:"north-carolina-to-new-york", from:"north-carolina", to:"new-york", fromName:"North Carolina", toName:"New York", distanceMiles:650, transitDays:"2–4", openPrice:"$480–$700", enclosedPrice:"$780–$1,050", topCitiesFrom:["Charlotte","Raleigh","Greensboro"], topCitiesTo:["New York City","Buffalo","Albany"] },
  { slug:"south-carolina-to-new-york", from:"south-carolina", to:"new-york", fromName:"South Carolina", toName:"New York", distanceMiles:780, transitDays:"2–4", openPrice:"$520–$750", enclosedPrice:"$820–$1,100", topCitiesFrom:["Charleston","Columbia","Greenville"], topCitiesTo:["New York City","Buffalo","Albany"] },
  { slug:"new-york-to-south-carolina", from:"new-york", to:"south-carolina", fromName:"New York", toName:"South Carolina", distanceMiles:780, transitDays:"2–4", openPrice:"$520–$750", enclosedPrice:"$820–$1,100", topCitiesFrom:["New York City","Buffalo","Albany"], topCitiesTo:["Charleston","Columbia","Myrtle Beach"] },
  { slug:"connecticut-to-south-carolina", from:"connecticut", to:"south-carolina", fromName:"Connecticut", toName:"South Carolina", distanceMiles:900, transitDays:"3–5", openPrice:"$580–$820", enclosedPrice:"$900–$1,200", topCitiesFrom:["Hartford","Bridgeport","New Haven"], topCitiesTo:["Charleston","Myrtle Beach","Columbia"] },
  { slug:"virginia-to-florida", from:"virginia", to:"florida", fromName:"Virginia", toName:"Florida", distanceMiles:1000, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Virginia Beach","Richmond","Arlington"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-virginia", from:"florida", to:"virginia", fromName:"Florida", toName:"Virginia", distanceMiles:1000, transitDays:"3–5", openPrice:"$600–$850", enclosedPrice:"$950–$1,250", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Virginia Beach","Richmond","Arlington"] },
  { slug:"maryland-to-florida", from:"maryland", to:"florida", fromName:"Maryland", toName:"Florida", distanceMiles:1100, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Baltimore","Rockville","Frederick"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-maryland", from:"florida", to:"maryland", fromName:"Florida", toName:"Maryland", distanceMiles:1100, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Baltimore","Rockville","Frederick"] },
  { slug:"new-jersey-to-california", from:"new-jersey", to:"california", fromName:"New Jersey", toName:"California", distanceMiles:2800, transitDays:"7–10", openPrice:"$1,050–$1,400", enclosedPrice:"$1,600–$2,100", topCitiesFrom:["Newark","Jersey City","Trenton"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"california-to-new-jersey", from:"california", to:"new-jersey", fromName:"California", toName:"New Jersey", distanceMiles:2800, transitDays:"7–10", openPrice:"$1,050–$1,400", enclosedPrice:"$1,600–$2,100", topCitiesFrom:["Los Angeles","San Francisco","San Diego"], topCitiesTo:["Newark","Jersey City","Trenton"] },

  // Additional popular routes
  { slug:"indiana-to-florida", from:"indiana", to:"florida", fromName:"Indiana", toName:"Florida", distanceMiles:1150, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Indianapolis","Fort Wayne","Evansville"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-indiana", from:"florida", to:"indiana", fromName:"Florida", toName:"Indiana", distanceMiles:1150, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Indianapolis","Fort Wayne","Evansville"] },
  { slug:"tennessee-to-florida", from:"tennessee", to:"florida", fromName:"Tennessee", toName:"Florida", distanceMiles:700, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Nashville","Memphis","Knoxville"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-tennessee", from:"florida", to:"tennessee", fromName:"Florida", toName:"Tennessee", distanceMiles:700, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Nashville","Memphis","Knoxville"] },
  { slug:"kentucky-to-florida", from:"kentucky", to:"florida", fromName:"Kentucky", toName:"Florida", distanceMiles:900, transitDays:"3–5", openPrice:"$580–$820", enclosedPrice:"$900–$1,200", topCitiesFrom:["Louisville","Lexington","Bowling Green"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-kentucky", from:"florida", to:"kentucky", fromName:"Florida", toName:"Kentucky", distanceMiles:900, transitDays:"3–5", openPrice:"$580–$820", enclosedPrice:"$900–$1,200", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Louisville","Lexington","Bowling Green"] },
  { slug:"iowa-to-florida", from:"iowa", to:"florida", fromName:"Iowa", toName:"Florida", distanceMiles:1600, transitDays:"4–7", openPrice:"$850–$1,150", enclosedPrice:"$1,300–$1,700", topCitiesFrom:["Des Moines","Cedar Rapids","Davenport"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-iowa", from:"florida", to:"iowa", fromName:"Florida", toName:"Iowa", distanceMiles:1600, transitDays:"4–7", openPrice:"$850–$1,150", enclosedPrice:"$1,300–$1,700", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Des Moines","Cedar Rapids","Davenport"] },
  { slug:"missouri-to-florida", from:"missouri", to:"florida", fromName:"Missouri", toName:"Florida", distanceMiles:1200, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Kansas City","St. Louis","Springfield"], topCitiesTo:["Miami","Orlando","Tampa"] },
  { slug:"florida-to-missouri", from:"florida", to:"missouri", fromName:"Florida", toName:"Missouri", distanceMiles:1200, transitDays:"3–5", openPrice:"$650–$900", enclosedPrice:"$1,000–$1,350", topCitiesFrom:["Miami","Orlando","Tampa"], topCitiesTo:["Kansas City","St. Louis","Springfield"] },
  { slug:"virginia-to-california", from:"virginia", to:"california", fromName:"Virginia", toName:"California", distanceMiles:2700, transitDays:"7–10", openPrice:"$1,050–$1,350", enclosedPrice:"$1,600–$2,050", topCitiesFrom:["Virginia Beach","Richmond","Arlington"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"maryland-to-california", from:"maryland", to:"california", fromName:"Maryland", toName:"California", distanceMiles:2700, transitDays:"7–10", openPrice:"$1,050–$1,350", enclosedPrice:"$1,600–$2,050", topCitiesFrom:["Baltimore","Rockville","Gaithersburg"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"pennsylvania-to-california", from:"pennsylvania", to:"california", fromName:"Pennsylvania", toName:"California", distanceMiles:2800, transitDays:"7–10", openPrice:"$1,050–$1,400", enclosedPrice:"$1,600–$2,100", topCitiesFrom:["Philadelphia","Pittsburgh","Allentown"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"massachusetts-to-california", from:"massachusetts", to:"california", fromName:"Massachusetts", toName:"California", distanceMiles:3000, transitDays:"8–11", openPrice:"$1,100–$1,450", enclosedPrice:"$1,650–$2,200", topCitiesFrom:["Boston","Worcester","Springfield"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"utah-to-california", from:"utah", to:"california", fromName:"Utah", toName:"California", distanceMiles:700, transitDays:"2–4", openPrice:"$480–$700", enclosedPrice:"$780–$1,050", topCitiesFrom:["Salt Lake City","Provo","West Jordan"], topCitiesTo:["Los Angeles","San Francisco","Las Vegas"] },
  { slug:"california-to-utah", from:"california", to:"utah", fromName:"California", toName:"Utah", distanceMiles:700, transitDays:"2–4", openPrice:"$480–$700", enclosedPrice:"$780–$1,050", topCitiesFrom:["Los Angeles","San Francisco","Las Vegas"], topCitiesTo:["Salt Lake City","Provo","West Jordan"] },
  { slug:"nevada-to-california", from:"nevada", to:"california", fromName:"Nevada", toName:"California", distanceMiles:270, transitDays:"1–2", openPrice:"$300–$500", enclosedPrice:"$550–$800", topCitiesFrom:["Las Vegas","Reno","Henderson"], topCitiesTo:["Los Angeles","San Diego","Bakersfield"] },
  { slug:"california-to-nevada", from:"california", to:"nevada", fromName:"California", toName:"Nevada", distanceMiles:270, transitDays:"1–2", openPrice:"$300–$500", enclosedPrice:"$550–$800", topCitiesFrom:["Los Angeles","San Diego","Bakersfield"], topCitiesTo:["Las Vegas","Reno","Henderson"] },
  { slug:"missouri-to-california", from:"missouri", to:"california", fromName:"Missouri", toName:"California", distanceMiles:2100, transitDays:"5–8", openPrice:"$950–$1,250", enclosedPrice:"$1,450–$1,900", topCitiesFrom:["Kansas City","St. Louis","Springfield"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"iowa-to-california", from:"iowa", to:"california", fromName:"Iowa", toName:"California", distanceMiles:2000, transitDays:"5–8", openPrice:"$950–$1,250", enclosedPrice:"$1,450–$1,900", topCitiesFrom:["Des Moines","Cedar Rapids","Davenport"], topCitiesTo:["Los Angeles","San Francisco","San Diego"] },
  { slug:"alaska-to-washington", from:"alaska", to:"washington", fromName:"Alaska", toName:"Washington", distanceMiles:2300, transitDays:"7–14", openPrice:"$1,200–$1,800", enclosedPrice:"$1,800–$2,600", topCitiesFrom:["Anchorage","Fairbanks","Juneau"], topCitiesTo:["Seattle","Tacoma","Bellingham"], notes:"Alaska transport involves ferry or multi-leg logistics — our advisors coordinate the full route." },
  { slug:"washington-to-alaska", from:"washington", to:"alaska", fromName:"Washington", toName:"Alaska", distanceMiles:2300, transitDays:"7–14", openPrice:"$1,200–$1,800", enclosedPrice:"$1,800–$2,600", topCitiesFrom:["Seattle","Tacoma","Bellingham"], topCitiesTo:["Anchorage","Fairbanks","Juneau"], notes:"Alaska transport involves ferry or multi-leg logistics — our advisors coordinate the full route." },
  { slug:"alabama-to-florida", from:"alabama", to:"florida", fromName:"Alabama", toName:"Florida", distanceMiles:380, transitDays:"1–3", openPrice:"$350–$550", enclosedPrice:"$600–$850", topCitiesFrom:["Birmingham","Mobile","Huntsville"], topCitiesTo:["Pensacola","Tampa","Orlando"] },
  { slug:"florida-to-alabama", from:"florida", to:"alabama", fromName:"Florida", toName:"Alabama", distanceMiles:380, transitDays:"1–3", openPrice:"$350–$550", enclosedPrice:"$600–$850", topCitiesFrom:["Pensacola","Tampa","Orlando"], topCitiesTo:["Birmingham","Mobile","Huntsville"] },
  { slug:"alabama-to-texas", from:"alabama", to:"texas", fromName:"Alabama", toName:"Texas", distanceMiles:700, transitDays:"2–4", openPrice:"$500–$750", enclosedPrice:"$800–$1,100", topCitiesFrom:["Birmingham","Mobile","Huntsville"], topCitiesTo:["Houston","Dallas","San Antonio"] },
  { slug:"alabama-to-georgia", from:"alabama", to:"georgia", fromName:"Alabama", toName:"Georgia", distanceMiles:160, transitDays:"1–2", openPrice:"$280–$450", enclosedPrice:"$500–$750", topCitiesFrom:["Birmingham","Huntsville","Montgomery"], topCitiesTo:["Atlanta","Columbus","Savannah"] },
  { slug:"louisiana-to-texas", from:"louisiana", to:"texas", fromName:"Louisiana", toName:"Texas", distanceMiles:350, transitDays:"1–3", openPrice:"$320–$520", enclosedPrice:"$570–$820", topCitiesFrom:["New Orleans","Baton Rouge","Shreveport"], topCitiesTo:["Houston","Dallas","San Antonio"] },
  { slug:"texas-to-louisiana", from:"texas", to:"louisiana", fromName:"Texas", toName:"Louisiana", distanceMiles:350, transitDays:"1–3", openPrice:"$320–$520", enclosedPrice:"$570–$820", topCitiesFrom:["Houston","Dallas","San Antonio"], topCitiesTo:["New Orleans","Baton Rouge","Shreveport"] },
  { slug:"oklahoma-to-texas", from:"oklahoma", to:"texas", fromName:"Oklahoma", toName:"Texas", distanceMiles:200, transitDays:"1–2", openPrice:"$280–$450", enclosedPrice:"$500–$750", topCitiesFrom:["Oklahoma City","Tulsa","Norman"], topCitiesTo:["Dallas","Fort Worth","Amarillo"] },
  { slug:"texas-to-oklahoma", from:"texas", to:"oklahoma", fromName:"Texas", toName:"Oklahoma", distanceMiles:200, transitDays:"1–2", openPrice:"$280–$450", enclosedPrice:"$500–$750", topCitiesFrom:["Dallas","Fort Worth","Amarillo"], topCitiesTo:["Oklahoma City","Tulsa","Norman"] },
  { slug:"new-hampshire-to-florida", from:"new-hampshire", to:"florida", fromName:"New Hampshire", toName:"Florida", distanceMiles:1500, transitDays:"4–7", openPrice:"$800–$1,100", enclosedPrice:"$1,250–$1,650", topCitiesFrom:["Manchester","Nashua","Concord"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-new-hampshire", from:"florida", to:"new-hampshire", fromName:"Florida", toName:"New Hampshire", distanceMiles:1500, transitDays:"4–7", openPrice:"$800–$1,100", enclosedPrice:"$1,250–$1,650", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Manchester","Nashua","Concord"] },
  { slug:"rhode-island-to-florida", from:"rhode-island", to:"florida", fromName:"Rhode Island", toName:"Florida", distanceMiles:1400, transitDays:"4–6", openPrice:"$750–$1,050", enclosedPrice:"$1,150–$1,550", topCitiesFrom:["Providence","Cranston","Warwick"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-rhode-island", from:"florida", to:"rhode-island", fromName:"Florida", toName:"Rhode Island", distanceMiles:1400, transitDays:"4–6", openPrice:"$750–$1,050", enclosedPrice:"$1,150–$1,550", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Providence","Cranston","Warwick"] },
  { slug:"vermont-to-florida", from:"vermont", to:"florida", fromName:"Vermont", toName:"Florida", distanceMiles:1550, transitDays:"4–7", openPrice:"$820–$1,100", enclosedPrice:"$1,270–$1,670", topCitiesFrom:["Burlington","Montpelier","Rutland"], topCitiesTo:["Miami","Orlando","Naples"] },
  { slug:"florida-to-vermont", from:"florida", to:"vermont", fromName:"Florida", toName:"Vermont", distanceMiles:1550, transitDays:"4–7", openPrice:"$820–$1,100", enclosedPrice:"$1,270–$1,670", topCitiesFrom:["Miami","Orlando","Naples"], topCitiesTo:["Burlington","Montpelier","Rutland"] },
];

export const routeBySlug: Record<string, RouteRecord> = Object.fromEntries(
  routesData.map((r) => [r.slug, r])
);
